version: '2.1'
services:
  videos-api:
    build: .
    environment:
      PORT: '5001'
      SHOW_URLS: 'true'
      VIDEOS_URL: '192.168.99.101'
      VIDEOS_PORT: '3002'
      VIDEOS_ENTRY: 'videos'
      CATEGORIES_URL: '192.168.99.101'
      CATEGORIES_PORT: '3002'
      CATEGORIES_ENTRY: 'categories'
      COMMENTS_URL: '192.168.99.101'
      COMMENTS_PORT: '3002'
      COMMENTS_ENTRY: 'comments'
      RECOMMENDATIONS_URL: '192.168.99.103'
      RECOMMENDATIONS_PORT: '8000'
      RECOMMENDATIONS_ENTRY: 'recommendations'
      COURSES_URL: '192.168.99.101'
      COURSES_PORT: '4000'
      COURSES_ENTRY: 'courses-ms/resources/courses' 
    ports:
      - '5001:5001'
