version: '2.1'
services:
  videos-api:
    build: .
    environment:
      PORT: '5001'
      SHOW_URLS: 'true'
      VIDEOS2_URL: '192.168.99.101'
      VIDEOS2_PORT: '3002'
      VIDEOS2_ENTRY: 'videos'
      CATEGORIES_URL: '192.168.99.101'
      CATEGORIES_PORT: '3002'
      CATEGORIES_ENTRY: 'categories'
      COMMENTARIES_ENTRY: feedback/resources/commentaries
      COMMENTARIES_PORT: '3004'
      COMMENTARIES_URL: '35.231.49.108'
      VIDEOS_URL: '192.168.99.101'
      VIDEOS_PORT: '3001'
      VIDEOS_ENTRY: 'uploadVideos'
      RECOMMENDATIONS_URL: '192.168.99.103'
      RECOMMENDATIONS_PORT: '3003'
      RECOMMENDATIONS_ENTRY: 'recommendations'
    ports:
      - '5001:5001'
