//export const url = process.env.COMMENTARIES_URL || 'feedback-ms'
//export const port = process.env.COMMENTARIES_PORT || '3004'
export const url = 'feedback-lb'
export const url = '4004'
export const entryPoint = process.env.COMMENTARIES_ENTRY || 'feedback/resources/commentaries'